import { Nunito } from "next/font/google";
import "./globals.css";
import Header from "./components/Header/Header";

const nunito = Nunito({ subsets: ["latin"] });

export const metadata = {
  title: "WeatherApp",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={nunito.className}>
        <div className=" h-screen flex flex-col   ">
          <Header />
          {children}
        </div>
      </body>
    </html>
  );
}
