export const citiesData = [
  { name: "Tokyo" },
  { name: "Jakarta" },
  { name: "Delhi" },
  { name: "Guangzhou" },
  { name: "Mumbai" },
  { name: "Manila" },
  { name: "Shanghai" },
  { name: "São Paulo" },
  { name: "Seoul" },
  { name: "Mexico City" },
  { name: "Cairo" },
  { name: "New York" },
  { name: "Dhaka" },
  { name: "Beijing" },
  { name: "Kolkata" },
  { name: "Bangkok" },
  { name: "Shenzhen" },
  { name: "Moscow" },
  { name: "Buenos Aires" },
  { name: "Lagos" },
  { name: "Istanbul" },
  { name: "Karachi" },
  { name: "Bangalore" },
  { name: "Ho Chi Minh City" },
  { name: "Ōsaka" },
  { name: "Chengdu" },
  { name: "Tehran" },
  { name: "Kinshasa" },
  { name: "Rio de Janeiro" },
  { name: "Chennai" },
  { name: "Xi’an" },
  { name: "Lahore" },
  { name: "Chongqing" },
  { name: "Los Angeles" },
  { name: "Baoding" },
  { name: "London" },
  { name: "Paris" },
  { name: "Linyi" },
  { name: "Dongguan" },
  { name: "Hyderābād" },
  { name: "Tianjin" },
  { name: "Lima" },
  { name: "Wuhan" },
  { name: "Nanyang" },
  { name: "Hangzhou" },
  { name: "Foshan" },
  { name: "Nagoya" },
  { name: "Tongshan" },
  { name: "Luanda" },
  { name: "Zhoukou" },
  { name: "Ganzhou" },
  { name: "Kuala Lumpur" },
  { name: "Heze" },
  { name: "Quanzhou" },
  { name: "Johannesburg" },
  { name: "Chicago" },
  { name: "Nanjing" },
  { name: "Jining" },
  { name: "Hanoi" },
  { name: "Pune" },
  { name: "Fuyang" },
  { name: "Ahmedabad" },
  { name: "Bogotá" },
  { name: "Shenyang" },
  { name: "Dar es Salaam" },
  { name: "Khartoum" },
  { name: "Shangqiu" },
  { name: "Hong Kong" },
  { name: "Cangzhou" },
  { name: "Riyadh" },
  { name: "Santiago" },
  { name: "Xingtai" },
  { name: "Zhumadian" },
  { name: "Chattogram" },
  { name: "Surabaya" },
  { name: "Zhanjiang" },
  { name: "Bijie" },
  { name: "Yancheng" },
  { name: "Hengyang" },
  { name: "Zunyi" },
  { name: "Shaoyang" },
  { name: "Sūrat" },
  { name: "Shangrao" },
  { name: "Xinyang" },
  { name: "Madrid" },
  { name: "Baghdad" },
  { name: "Maoming" },
  { name: "Jieyang" },
  { name: "Miami" },
  { name: "Singapore" },
  { name: "Houston" },
  { name: "Liaocheng" },
  { name: "Huanggang" },
  { name: "Dalian" },
  { name: "Dallas" },
  { name: "Qingdao" },
  { name: "Yulin" },
  { name: "Douala" },
  { name: "Qujing" },
  { name: "Nangandao" },
  { name: "Philadelphia" },
  { name: "Pudong" },
  { name: "Toronto" },
  { name: "Zhengzhou" },
  { name: "Dezhou" },
  { name: "Nanchong" },
  { name: "Jinan" },
  { name: "Giza" },
  { name: "Nairobi" },
  { name: "Guadalajara" },
  { name: "Ankara" },
  { name: "Tai’an" },
  { name: "Langfang" },
  { name: "Dazhou" },
  { name: "Saint Petersburg" },
  { name: "Monterrey" },
  { name: "Belo Horizonte" },
  { name: "Suzhou" },
  { name: "Yongzhou" },
  { name: "Changde" },
  { name: "Xiangyang" },
  { name: "Rangoon" },
  { name: "Atlanta" },
  { name: "Washington" },
  { name: "Zhaotong" },
  { name: "Zhangzhou" },
  { name: "Melbourne" },
  { name: "Yichun" },
  { name: "Bozhou" },
  { name: "Suqian" },
  { name: "Abidjan" },
  { name: "Ji’an" },
  { name: "Guilin" },
  { name: "Pingdingshan" },
  { name: "Berlin" },
  { name: "Alexandria" },
  { name: "Mianyang" },
  { name: "Sydney" },
  { name: "Huanglongsi" },
  { name: "Barcelona" },
  { name: "Yuncheng" },
  { name: "Cape Town" },
  { name: "Changsha" },
  { name: "Jeddah" },
  { name: "Weinan" },
  { name: "Chenzhou" },
  { name: "Jiangmen" },
  { name: "Jiujiang" },
  { name: "Xinpu" },
  { name: "Yibin" },
  { name: "Huaihua" },
  { name: "Yangzhou" },
  { name: "Taizhou" },
  { name: "Kunming" },
  { name: "Yiyang" },
  { name: "Changchun" },
  { name: "Hefei" },
  { name: "Nanning" },
  { name: "Changzhou" },
  { name: "Qiqihar" },
  { name: "Fuzhou" },
  { name: "Harbin" },
  { name: "Chifeng" },
  { name: "Loudi" },
  { name: "Zhuzhou" },
  { name: "Taiyuan" },
  { name: "Anqing" },
  { name: "Liuzhou" },
  { name: "Zhangjiakou" },
  { name: "Zhaoqing" },
  { name: "Shijiazhuang" },
  { name: "Ningbo" },
  { name: "Phoenix" },
  { name: "Xiaoxita" },
  { name: "Chuzhou" },
  { name: "Linfen" },
  { name: "Qingyuan" },
  { name: "Xianyang" },
  { name: "Binzhou" },
  { name: "Zhuzhou" },
  { name: "Nanning" },
  { name: "Harbin" },
  { name: "Chifeng" },
  { name: "Xiaoxita" },
  { name: "Chuzhou" },
  { name: "Linfen" },
  { name: "Qingyuan" },
  { name: "Xianyang" },
  { name: "Loudi" },
  { name: "Binzhou" },
  { name: "Zhuzhou" },
  { name: "Taiyuan" },
  { name: "Nanning" },
  { name: "Harbin" },
  { name: "Abuja" },
  { name: "Suihua" },
  { name: "Zaozhuang" },
  { name: "Detroit" },
  { name: "Xiamen" },
  { name: "Neijiang" },
  { name: "Fuzhou" },
  { name: "Wuhu" },
  { name: "Yulinshi" },
  { name: "Wenzhou" },
  { name: "Changzhou" },
  { name: "Puyang" },
  { name: "Jiaozuo" },
  { name: "Nanchang" },
  { name: "Baicheng" },
  { name: "Deyang" },
  { name: "Hechi" },
  { name: "Tangshan" },
  { name: "Shiyan" },
  { name: "Lucknow" },
  { name: "San Francisco" },
  { name: "Dubai" },
  { name: "Anshan" },
  { name: "Baojishi" },
  { name: "Qinzhou" },
  { name: "Guiyang" },
  { name: "Bengbu" },
  { name: "Bazhou" },
  { name: "Suining" },
  { name: "Wuxi" },
  { name: "Xinzhou" },
  { name: "Lanzhou" },
  { name: "Wuzhou" },
  { name: "Hanzhong" },
  { name: "Putian" },
  { name: "Zhenjiang" },
  { name: "Guang’an" },
  { name: "Changzhi" },
  { name: "Tongren" },
  { name: "Leshan" },
  { name: "Qinhuangdao" },
  { name: "Xiamen" },
  { name: "Neijiang" },
  { name: "Fuzhou" },
  { name: "Wuhu" },
  { name: "Yulinshi" },
  { name: "Wenzhou" },
  { name: "Changzhou" },
  { name: "Puyang" },
  { name: "Jiaozuo" },
  { name: "Nanchang" },
  { name: "Baicheng" },
  { name: "Deyang" },
  { name: "Hechi" },
  { name: "Tangshan" },
  { name: "Shiyan" },
  { name: "Lucknow" },
  { name: "San Francisco" },
  { name: "Dubai" },
  { name: "Anshan" },
  { name: "Baojishi" },
  { name: "Qinzhou" },
  { name: "Guiyang" },
  { name: "Bengbu" },
  { name: "Bazhou" },
  { name: "Suining" },
  { name: "Wuxi" },
  { name: "Xinzhou" },
  { name: "Lanzhou" },
  { name: "Wuzhou" },
  { name: "Hanzhong" },
  { name: "Putian" },
  { name: "Zhenjiang" },
  { name: "Guang’an" },
  { name: "Faisalabad" },
  { name: "Changzhi" },
  { name: "Tongren" },
  { name: "Leshan" },
  { name: "Santa Cruz de la Sierra" },
  { name: "Qinhuangdao" },
  { name: "Jaipur" },
  { name: "Xinzhou" },
  { name: "Lanzhou" },
  { name: "Wuzhou" },
  { name: "Athens" },
  { name: "San Diego" },
  { name: "Addis Ababa" },
  { name: "Huainan" },
  { name: "Guatemala City" },
  { name: "Kuwait City" },
  { name: "Qincheng" },
  { name: "Rizhao" },
  { name: "Quezon City" },
  { name: "Sanaa" },
  { name: "Tashkent" },
  { name: "Kyiv" },
  { name: "Meishan" },
  { name: "Incheon" },
  { name: "Birmingham" },
  { name: "Ningde" },
  { name: "Zhongshan" },
  { name: "Weihai" },
  { name: "Bursa" },
  { name: "Minneapolis" },
  { name: "Mbuji-Mayi" },
  { name: "Haikou" },
  { name: "Tongliao" },
  { name: "Chaoyang" },
  { name: "La Paz" },
  { name: "Pyongyang" },
  { name: "Tampa" },
  { name: "Shaoguan" },
  { name: "Heyuan" },
  { name: "Omdurman" },
  { name: "Malang" },
  { name: "Stuttgart" },
  { name: "Rotherham", country: "United Kingdom" },
  { name: "Dera Ismail Khan", country: "Pakistan" },
  { name: "Esteban Echeverría", country: "Argentina" },
  { name: "Quezon", country: "Philippines" },
  { name: "Aguachica", country: "Colombia" },
  { name: "Naujan", country: "Philippines" },
  { name: "Glan", country: "Philippines" },
  { name: "Bayugan", country: "Philippines" },
  { name: "Eau Claire", country: "United States" },
  { name: "Brovary", country: "Ukraine" },
  { name: "Gualeguaychú", country: "Argentina" },
  { name: "Delft", country: "Netherlands" },
  { name: "Walthamstow", country: "United Kingdom" },
  { name: "Drammen", country: "Norway" },
  { name: "Medenine", country: "Tunisia" },
  { name: "Nkpor", country: "Nigeria" },
  { name: "Kamagaya", country: "Japan" },
  { name: "Tacurong", country: "Philippines" },
  { name: "Malacatán", country: "Guatemala" },
  { name: "Taoyang", country: "China" },
  { name: "Béja", country: "Tunisia" },
  { name: "Yŏngju", country: "Korea, South" },
  { name: "Labo", country: "Philippines" },
  { name: "Sandachō", country: "Japan" },
  { name: "Berkane", country: "Morocco" },
  { name: "Sầm Sơn", country: "Vietnam" },
  { name: "White Rock", country: "Canada" },
  { name: "Marugame", country: "Japan" },
  { name: "Tangjia", country: "China" },
  { name: "Sehore", country: "India" },
  { name: "Murom", country: "Russia" },
  { name: "Soma", country: "Turkey" },
  { name: "Handeni", country: "Tanzania" },
  { name: "Balombo", country: "Angola" },
  { name: "Talisay", country: "Philippines" },
  { name: "Taitung", country: "Taiwan" },
  { name: "Bangaon", country: "India" },
  { name: "Dolgoprudnyy", country: "Russia" },
  { name: "Thunder Bay", country: "Canada" },
  { name: "Pulilan", country: "Philippines" },
  { name: "Maxixe", country: "Mozambique" },
  { name: "Kasserine", country: "Tunisia" },
  { name: "Bagu Na Mohra", country: "Pakistan" },
  { name: "Maţrūḩ", country: "Egypt" },
  { name: "Baia Mare", country: "Romania" },
  { name: "Shihuajie", country: "China" },
  { name: "Tondabayashichō", country: "Japan" },
  { name: "Bà Rịa", country: "Vietnam" },
  { name: "El Monte", country: "United States" },
  { name: "Witbank", country: "South Africa" },
  { name: "Khopoli", country: "India" },
  { name: "Ferizaj", country: "Kosovo" },
  { name: "Xishancun", country: "China" },
  { name: "Mascara", country: "Algeria" },
  { name: "Khenchela", country: "Algeria" },
  { name: "Taungoo", country: "Burma" },
  { name: "Móng Cái", country: "Vietnam" },
  { name: "Idaho Falls", country: "United States" },
  { name: "Melipilla", country: "Chile" },
  { name: "Komatsu", country: "Japan" },
  { name: "Islāmābād", country: "India" },
  { name: "Yāsūj", country: "Iran" },
  { name: "Khardah", country: "India" },
  { name: "Cawayan", country: "Philippines" },
  { name: "Reus", country: "Spain" },
  { name: "Mopti", country: "Mali" },
  { name: "Delta", country: "Canada" },
  { name: "Dearborn", country: "United States" },
  { name: "Toowoomba", country: "Australia" },
  { name: "Mungeli", country: "India" },
  { name: "Bloomington", country: "United States" },
  { name: "Alto Hospicio", country: "Chile" },
  { name: "Habikino", country: "Japan" },
  { name: "Novoshakhtinsk", country: "Russia" },
  { name: "Maramag", country: "Philippines" },
  { name: "Yevpatoriia", country: "Ukraine" },
  { name: "Caen", country: "France" },
  { name: "Nantang", country: "China" },
  { name: "West Covina", country: "United States" },
  { name: "Tādpatri", country: "India" },
  { name: "Birnin Kebbi", country: "Nigeria" },
  { name: "Acharnés", country: "Greece" },
  { name: "Yilong", country: "China" },
  { name: "Sarh", country: "Chad" },
  { name: "Sparks", country: "United States" },
  { name: "Mudanya", country: "Turkey" },
  { name: "Miami Gardens" },
  { name: "Chilón" },
  { name: "Chiquimula" },
  { name: "Sabara Bangou" },
  { name: "Costa Mesa" },
  { name: "Baleraja" },
  { name: "Montreuil" },
  { name: "Villa Mercedes" },
  { name: "Sioux City" },
  { name: "Ghotki" },
  { name: "Jawhar" },
  { name: "Santamesa" },
  { name: "Kasempa" },
  { name: "Champdani" },
  { name: "São Lourenço da Mata" },
  { name: "Ḩaraḑ" },
  { name: "Jena" },
  { name: "Gafsa" },
  { name: "Ariquemes" },
  { name: "Kasuga" },
  { name: "Kamyshin" },
  { name: "Nsukka" },
  { name: "Kintampo" },
  { name: "Nandurbar" },
  { name: "Purwa Utar" },
  { name: "Tuzla" },
  { name: "Namur" },
  { name: "Khushab" },
  { name: "Everett" },
  { name: "Puerto Barrios" },
  { name: "Fasā" },
  { name: "Rosario" },
  { name: "Gilroy" },
  { name: "Kiffa" },
  { name: "Al Aḩad al Masāriḩah" },
  { name: "As Salamīyah" },
  { name: "Sorriso" },
  { name: "Franceville" },
  { name: "San Antonio Enchisi" },
  { name: "Quíbor" },
  { name: "Socopó" },
  { name: "Ahuachapán" },
  { name: "Manzini" },
  { name: "Masindi" },
  { name: "Muktsar" },
  { name: "Martínez de la Torre" },
  { name: "San Buenaventura" },
  { name: "Changbang" },
  { name: "Empangeni" },
  { name: "Ferozepore" },
  { name: "Bāneh" },
  { name: "Itele" },
  { name: "Rochdale" },
  { name: "Jeonghae" },
  { name: "Shirayamamachi" },
  { name: "Temecula" },
  { name: "Tubarão" },
  { name: "Sugar Land" },
  { name: "Ōmuta" },
  { name: "Chico" },
  { name: "Msaken" },
  { name: "Tinaquillo" },
  { name: "Bridgetown" },
  { name: "Wythenshawe" },
  { name: "Mancherāl" },
  { name: "Qal‘at Sukkar" },
  { name: "Pisco" },
  { name: "Retalhuleu" },
  { name: "Bernal" },
  { name: "Sutton Coldfield" },
  { name: "Vicenza" },
  { name: "Doncaster" },
  { name: "Winterthur" },
  { name: "Dali" },
  { name: "Rotherham" },
  { name: "Dera Ismail Khan" },
  { name: "Esteban Echeverría" },
  { name: "Quezon" },
  { name: "Aguachica" },
  { name: "Naujan" },
  { name: "Glan" },
  { name: "Bayugan" },
  { name: "Eau Claire" },
  { name: "Brovary" },
  { name: "Gualeguaychú" },
  { name: "Delft" },
  { name: "Walthamstow" },
  { name: "Drammen" },
  { name: "Medenine" },
  { name: "Nkpor" },
  { name: "Kamagaya" },
  { name: "Tacurong" },
  { name: "Malacatán" },
  { name: "Taoyang" },
  { name: "Béja" },
  { name: "Yŏngju" },
  { name: "Labo" },
  { name: "Sandachō" },
  { name: "Berkane" },
  { name: "Sầm Sơn" },
  { name: "White Rock" },
  { name: "Marugame" },
  { name: "Tangjia" },
  { name: "Sehore" },
  { name: "Murom" },
  { name: "Soma" },
];





// {clickedCity.length > 2 ? (
//   <div className="flex flex-col absolute w-full ">
//     {
//       filtered.map((item, idx) => (
//         <Link
//           key={idx}
//           onClick={getCity}
//           href={`/${item.name || item}`}
//           className="w-full h-14 text-base-100 flex transition-all bg-popover
//             items-center pl-6 rounded-lg"
//         >
//           {item.name || item}
//         </Link>
//       ))}
//   </div>
// ) : (
//   ""
// )}